### ISSUE TITLE
Touch Priority Issues

### ISSUE THREAD

**Issue by sheepdotcom** [M336G/AutoLeaderboard#1]
Somehow you made the LevelInfoLayer take priority over all other popups which means it makes it impossible to interact with items in popups.

**Comment by M336G** [comment]
Could you describe your issue a little bit more? Maybe the leaderboard did not have time to close itself.

**Comment by sheepdotcom** [comment]
Unable to replicate it anymore

**Comment by M336G** [comment]
Will put this on hold for now then
